name: Build and Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: 3.11

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
    
      - name: install postgres
        run: |
          sudo apt update
          sudo apt install postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          sudo -i -u postgres

      - name: Create and connect to a db
        run: |
          createdb chitter_test
          psql -h localhost -U postgres -d chitter_test


      - name: Update playwright
        run: | 
          pipenv install playwright
          pipenv run playwright install

      - name: Test with pytest
        run: |
          pipenv run pytest