name: Build and Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: 3.11

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test with pytest
        run: |
          pipenv run pytest